### PR TITLE
Fix Thermal Expansion furnace recipes for Natura and Twilight Forest woods to charcoal

### PR DESCRIPTION
**Pull request by redelman**
Fix Thermal Expansion furnace recipes for Natura and Twilight Forest
woods to charcoal. Also removed the unused val for ore:logWood, and
shortened the config a lot by globbing on metadata.

### CODE REVIEW

**Comment by redelman** [comment]
Ugh don't apply this :/

**Comment by TomeWyrm** [comment]
Aww, Why not?

**Comment by redelman** [comment]
Because I used github desktop to create this instead of git cli (which is much much better) and didn't branch for the stuff like I should have. :/

**Comment by TomeWyrm** [comment]
I can't stand the CLI, personally :-)

**Pull request closed without merging**
